# Generated by Django 4.1.7 on 2023-03-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Orders', models.CharField(max_length=100)),
                ('Ordered_items', models.CharField(max_length=100)),
            ],
        ),
    ]
