# Generated by Django 4.1.7 on 2023-03-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='Ordered_items',
        ),
        migrations.RemoveField(
            model_name='display',
            name='Orders',
        ),
    ]
